import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { kudaModena, suisseIntl } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-theme="retail-light"
      className={cn(
        "h-full",
        "antialiased",
        "font-sans",
        suisseIntl.variable,
        kudaModena.variable
      )}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
