import StyleDictionary from 'style-dictionary'
import { promises as fs } from 'fs'

// ─── Custom transforms ────────────────────────────────────────────────────────

StyleDictionary.registerTransform({
  name: 'size/pxToRem',
  type: 'value',
  filter: (token) =>
    (token.$type ?? token.type) === 'number' &&
    token.path.some((p) => p === 'size'),
  transform: (token) => `${(token.$value ?? token.value) / 16}rem`,
})

StyleDictionary.registerTransform({
  name: 'size/px',
  type: 'value',
  filter: (token) => {
    if (token.path[0] === 'spacing' && token.path[1] === '1') {
      console.log('DEBUG size/px FILTER CALLED! $type:', JSON.stringify(token.$type), 'type:', JSON.stringify(token.type), 'path:', token.path)
      return true
    }
    const typeMatch = (token.$type ?? token.type) === 'number'
    const notOpacity = token.path[0] !== 'opacity'
    const notSize = !token.path.some((p) => p === 'size')
    const notWeight = !token.path.some((p) => p === 'weight')
    const notFamily = !token.path.some((p) => p === 'family')
    return typeMatch && notOpacity && notSize && notWeight && notFamily
  },
  transform: (token) => {
    const v = token.$value ?? token.value
    if (token.path[0] === 'spacing' && token.path[1] === '1') console.log('DEBUG size/px TRANSFORM FIRED, v=', v)
    return v === 0 ? '0' : `${v}px`
  },
})

StyleDictionary.registerTransform({
  name: 'opacity/fraction',
  type: 'value',
  filter: (token) =>
    (token.$type ?? token.type) === 'number' && token.path[0] === 'opacity',
  transform: (token) => (token.$value ?? token.value) / 100,
})

StyleDictionary.registerTransform({
  name: 'name/kuda',
  type: 'name',
  transform: (token) => {
    const name = token.path
      .join('-')
      .replace(/,/g, '-')
      .replace(/\*/g, '')
      .replace(/-+/g, '-')
      .replace(/-$/, '')
    return `k-${name}`
  },
})

// ─── Transform groups ─────────────────────────────────────────────────────────

StyleDictionary.registerTransformGroup({
  name: 'kuda/css',
  transforms: [
    'name/kuda',
    'size/pxToRem',
    'size/px',
    'opacity/fraction',
    'color/css',
  ],
})

// ─── Theme configurations ─────────────────────────────────────────────────────

const themes = [
  {
    name: 'retail-light',
    selector: '[data-theme="retail-light"]',
    sources: [
      'tokens/raw/token_Color_Mode1.json',
      'tokens/raw/token_Theme_RetailLight.json',
    ],
  },
  {
    name: 'retail-dark',
    selector: '[data-theme="retail-dark"]',
    sources: [
      'tokens/raw/token_Color_Mode1.json',
      'tokens/raw/token_Theme_RetailDark.json',
    ],
  },
  {
    name: 'business-light',
    selector: '[data-theme="business-light"]',
    sources: [
      'tokens/raw/token_Color_Mode1.json',
      'tokens/raw/token_Theme_BusinessLight.json',
    ],
  },
  {
    name: 'business-dark',
    selector: '[data-theme="business-dark"]',
    sources: [
      'tokens/raw/token_Color_Mode1.json',
      'tokens/raw/token_Theme_BusinessDark.json',
    ],
  },
]

const sharedFiles = [
  { name: 'spacing', source: 'tokens/raw/token_Spacing_Mode1.json' },
  { name: 'sizing', source: 'tokens/raw/token_Sizing_Mode1.json' },
  { name: 'typography', source: 'tokens/raw/token_Typography_Mode1.json' },
  { name: 'radius', source: 'tokens/raw/token_Radius_Mode1.json' },
  { name: 'stroke-width', source: 'tokens/raw/token_StrokeWidth_Mode1.json' },
  { name: 'opacity', source: 'tokens/raw/token_Opacity_Mode1.json' },
]

// ─── Build functions ──────────────────────────────────────────────────────────

async function buildTheme(theme) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: theme.sources,
    platforms: {
      css: {
        transformGroup: 'kuda/css',
        buildPath: 'tokens/output/',
        files: [
          {
            destination: `${theme.name}.css`,
            format: 'css/variables',
            options: {
              selector: theme.selector,
              outputReferences: true,
              fileHeader: () => [
                'do not edit — generated by Style Dictionary',
                `theme: ${theme.name}`,
              ],
            },
          },
        ],
      },
    },
  })

  await sd.buildAllPlatforms()
}

async function buildSharedFile(file) {
  const rawJson = JSON.parse(await fs.readFile(file.source, 'utf8'))
  const sd = new StyleDictionary({
    usesDtcg: true,
    tokens: { [file.name]: rawJson },
    platforms: {
      css: {
        transformGroup: 'kuda/css',
        buildPath: 'tokens/output/',
        files: [
          {
            destination: `${file.name}.css`,
            format: 'css/variables',
            options: {
              selector: ':root',
              outputReferences: true,
              fileHeader: () => [
                'do not edit — generated by Style Dictionary',
                `shared tokens: ${file.name}`,
              ],
            },
          },
        ],
      },
    },
  })

  await sd.buildAllPlatforms()
}

async function main() {
  await fs.mkdir('tokens/output', { recursive: true })

  for (const file of sharedFiles) {
    await buildSharedFile(file)
  }

  for (const theme of themes) {
    await buildTheme(theme)
  }

  console.log('✓ All token builds complete')
}

main().catch((err) => {
  console.error('Token build failed:', err)
  process.exit(1)
})