import StyleDictionary from 'style-dictionary'

const sd = new StyleDictionary({
  source: ['tokens/raw/**/*.json'],

  platforms: {

    css: {
      transformGroup: 'css',
      buildPath: 'tokens/output/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            selector: ':root',
            outputReferences: true,
            fileHeader: 'do not edit — generated by Style Dictionary from tokens/raw',
          },
        },
      ],
    },

    ts: {
      transformGroup: 'js',
      buildPath: 'tokens/output/',
      files: [
        {
          destination: 'tokens.ts',
          format: 'javascript/es6',
        },
      ],
    },

  },
})

await sd.buildAllPlatforms()