import StyleDictionary from 'style-dictionary'
import { promises as fs } from 'fs'

// ─── Custom transforms ────────────────────────────────────────────────────────

const REM_BASE_PX = 16

function getTokenType(token) {
  return token.$type ?? token.type
}

function getTokenValue(token) {
  return token.$value ?? token.value
}

function isNumberToken(token) {
  return getTokenType(token) === 'number'
}

function isRemToken(token) {
  const [category, type] = token.path

  return (
    category === 'spacing' ||
    category === 'sizing' ||
    category === 'radius' ||
    (category === 'typography' &&
      ['letter-spacing', 'line-height', 'size'].includes(type))
  )
}

function pxToRem(value) {
  return value === 0 ? '0' : `${value / REM_BASE_PX}rem`
}

StyleDictionary.registerTransform({
  name: 'kuda/size/pxToRem',
  type: 'value',
  filter: (token) => isNumberToken(token) && isRemToken(token),
  transform: (token) => pxToRem(getTokenValue(token)),
})

StyleDictionary.registerTransform({
  name: 'kuda/size/px',
  type: 'value',
  filter: (token) => {
    const typeMatch = isNumberToken(token)
    const notOpacity = token.path[0] !== 'opacity'
    const notRemToken = !isRemToken(token)
    const notWeight = !token.path.some((p) => p === 'weight')
    const notFamily = !token.path.some((p) => p === 'family')
    return typeMatch && notOpacity && notRemToken && notWeight && notFamily
  },
  transform: (token) => {
    const v = getTokenValue(token)
    return v === 0 ? '0' : `${v}px`
  },
})

StyleDictionary.registerTransform({
  name: 'opacity/fraction',
  type: 'value',
  filter: (token) => isNumberToken(token) && token.path[0] === 'opacity',
  transform: (token) => getTokenValue(token) / 100,
})

StyleDictionary.registerTransform({
  name: 'name/kuda',
  type: 'name',
  transform: (token) => {
    const name = token.path
      .join('-')
      .replace(/,/g, '-')
      .replace(/\*/g, '')
      .replace(/-+/g, '-')
      .replace(/-$/, '')
    return `k-${name}`
  },
})

// ─── Transform groups ─────────────────────────────────────────────────────────

StyleDictionary.registerTransformGroup({
  name: 'kuda/css',
  transforms: [
    'name/kuda',
    'kuda/size/pxToRem',
    'kuda/size/px',
    'opacity/fraction',
    'color/css',
  ],
})

// ─── Theme configurations ─────────────────────────────────────────────────────

const themes = [
  {
    name: 'retail-light',
    selector: '[data-theme="retail-light"]',
    sources: [
      'tokens/raw/token_Color_Mode1.json',
      'tokens/raw/token_Theme_RetailLight.json',
    ],
  },
  {
    name: 'retail-dark',
    selector: '[data-theme="retail-dark"]',
    sources: [
      'tokens/raw/token_Color_Mode1.json',
      'tokens/raw/token_Theme_RetailDark.json',
    ],
  },
  {
    name: 'business-light',
    selector: '[data-theme="business-light"]',
    sources: [
      'tokens/raw/token_Color_Mode1.json',
      'tokens/raw/token_Theme_BusinessLight.json',
    ],
  },
  {
    name: 'business-dark',
    selector: '[data-theme="business-dark"]',
    sources: [
      'tokens/raw/token_Color_Mode1.json',
      'tokens/raw/token_Theme_BusinessDark.json',
    ],
  },
]

const sharedFiles = [
  { name: 'spacing', source: 'tokens/raw/token_Spacing_Mode1.json' },
  { name: 'sizing', source: 'tokens/raw/token_Sizing_Mode1.json' },
  { name: 'typography', source: 'tokens/raw/token_Typography_Mode1.json' },
  { name: 'radius', source: 'tokens/raw/token_Radius_Mode1.json' },
  { name: 'stroke-width', source: 'tokens/raw/token_StrokeWidth_Mode1.json' },
  { name: 'opacity', source: 'tokens/raw/token_Opacity_Mode1.json' },
]

// ─── Build functions ──────────────────────────────────────────────────────────

async function buildTheme(theme) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    source: theme.sources,
    platforms: {
      css: {
        transformGroup: 'kuda/css',
        buildPath: 'tokens/output/',
        files: [
          {
            destination: `${theme.name}.css`,
            format: 'css/variables',
            options: {
              selector: theme.selector,
              outputReferences: true,
              fileHeader: () => [
                'do not edit — generated by Style Dictionary',
                `theme: ${theme.name}`,
              ],
            },
          },
        ],
      },
    },
  })

  await sd.buildAllPlatforms()
}

async function buildSharedFile(file) {
  const rawJson = JSON.parse(await fs.readFile(file.source, 'utf8'))
  const sd = new StyleDictionary({
    usesDtcg: true,
    tokens: { [file.name]: rawJson },
    platforms: {
      css: {
        transformGroup: 'kuda/css',
        buildPath: 'tokens/output/',
        files: [
          {
            destination: `${file.name}.css`,
            format: 'css/variables',
            options: {
              selector: ':root',
              outputReferences: true,
              fileHeader: () => [
                'do not edit — generated by Style Dictionary',
                `shared tokens: ${file.name}`,
              ],
            },
          },
        ],
      },
    },
  })

  await sd.buildAllPlatforms()
}

async function main() {
  await fs.mkdir('tokens/output', { recursive: true })

  for (const file of sharedFiles) {
    await buildSharedFile(file)
  }

  for (const theme of themes) {
    await buildTheme(theme)
  }

  console.log('✓ All token builds complete')
}

main().catch((err) => {
  console.error('Token build failed:', err)
  process.exit(1)
})
